apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring   # debe coincidir con el release de prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}